### PR TITLE
Mapping

### PR DESCRIPTION
**Pull request by elespdn**

### CODE REVIEW

**Comment by elespdn** [comment]
Name of the folder containing everything about the standoff mapping changed from 'text-encoding' to 'mapping'. It contains all files needed to manage TEI content within the project: a customized standoff onto and associated XML file, following Knora requirements; the XSLT to transform XML into HTML; the files to load these resources into Knora and info about how to do it.

**Comment by elespdn** [comment]
Ready for prod

**Comment by loicjaouen** [comment]
upload of the standoff ontology

**Comment by loicjaouen** [comment]
upload on local triple store:
```bash
./load-fuseki.sh
```

**Comment by loicjaouen** [comment]
last commit fixes the iri of the xslt resource, so we don't have to grab the iri, replace it in the mapping description in the xml file

**Comment by loicjaouen** [comment]
fully tested locally:
- set-up of the local stack
- run step-by-step the requests in `import-mapping.rest`

**Pull request merged**
