### PR TITLE
bulk import of scans (mss and pubs)

### PR DESCRIPTION
**Pull request by elespdn**
Added one XML file for testing the import of images, together with the image file.

### CODE REVIEW

**Comment by elespdn** [comment]
Upload can be done using the command `xmlupload` of dsp-tools, as described here: https://docs.dasch.swiss/2022.07.01/DSP-TOOLS/dsp-tools-usage/#upload-data-to-a-dsp-server

Because there are links to existing resources, use the option `--incremental` (also mentioned in the [bulk import doc](https://docs.dasch.swiss/2022.07.01/DSP-TOOLS/dsp-tools-xmlupload/))

**Comment by elespdn** [comment]
Export a list of shelfmark and corresponding IRI from db

```sparql
PREFIX roud-oeuvres: <http://www.knora.org/ontology/0112/roud-oeuvres#>
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
select ?msIri ?shelfmark where { 
	?msIri roud-oeuvres:manuscriptHasShelfmark  ?shelfmarkIri .
    ?shelfmarkIri knora-base:valueHasString ?shelfmark .
    ?msIri knora-base:isDeleted false .
}
```

**Comment by elespdn** [comment]
XML created!

Find solution for problematic images listed at https://github.com/LaDHUL/oeuvres-roud/issues/62#issuecomment-1172372926

**Comment by elespdn** [comment]
### Import of scans of publications (pubs)

**Comment by elespdn** [comment]
Export a list of label and corresponding IRI from db

```sparql
PREFIX roud-oeuvres: <http://www.knora.org/ontology/0112/roud-oeuvres#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?pubIri ?label where {
    ?pubIri a roud-oeuvres:PeriodicalArticle .
    ?pubIri rdfs:label ?label .
}
```

**Comment by loicjaouen** [comment]
# mss

imported mostly fine, 11 errors out of 1968 imports, there are two kinds of errors

- missing image files
  ```
  /mnt/scanlettMounted/GustaveRoud/E_Scan/Scans_complets/FondsArchive/CRLR_GR_MS6B310a/CRLR_GR_MS6B310a_1r_1.tif
  /mnt/scanlettMounted/GustaveRoud/E_Scan/Scans_complets/FondsArchive/CRLR_GR_MS6B310a/CRLR_GR_MS6B310a_2r_2.tif
  /mnt/scanlettMounted/GustaveRoud/E_Scan/Scans_complets/FondsArchive/CRLR_GR_MS6B310a/CRLR_GR_MS6B310a_3r_3.tif
  /mnt/scanlettMounted/GustaveRoud/E_Scan/Scans_complets/FondsArchive/CRLR_GR_MS6B310a/CRLR_GR_MS6B310a_4r_4.tif
  /mnt/scanlettMounted/GustaveRoud/E_Scan/Scans_complets/FondsArchive/CRLR_GR_MS6B310a/CRLR_GR_MS6B310a_5r_5.tif
  /mnt/scanlettMounted/GustaveRoud/E_Scan/Scans_complets/FondsArchive/CRLR_GR_MS6B310a/CRLR_GR_MS6B310a_6r_6.tif
  ```
  at first glance it looks like a typo in the file names

- xml validation error for:
  ```
  importCRLR_GR_MS6B26a_1v_2a.xml
  importCRLR_GR_MS6B33a_3v_6a.xml
  importCRLR_GR_MS6C213a_3v_6a.xml
  importCRLR_GR_MS6C24a_3r_5a.xml
  importCRLR_GR_MS6G53a_5r_5a.xml
  ``` 
  that is because the page number `2a` is turned into an integer... which it is not

**Comment by loicjaouen** [comment]
# pubs

done, there were three page missing after the initial import, they failed silently without the page being imported, they are now all there after calling the import request for these three resources.

**Comment by loicjaouen** [comment]
the import ran without a glitch

**Pull request merged**
